language: node_js
node_js:
- 12
cache: npm
install:
- npm ci
addons:
  sonarcloud:
    organization: programming101tutorial
    token:
      secure: ZANmuTqAD7IiQXINyPFyl7S8SifnUU90/OZC0ZCsNQ5clL9f0vyeWGIUykH5aBPqaZTfinRQDAxaM8P12IsgEHM994GqFrg0w+eX5o0vFfJ9UPGb+2FEGKt4KDjDTrxIi8FXLwLU9vGC2aXcf2dPMXhFrqDetudeH3OorUtUohFQ8gmiGfnLerYGc0LbuVLK97R5iuhXPzgvsosGd42Mpyu9pKapc2NmLnk6+5RpXrvbeRgbKFQIMt4/OyYLLgjJ045xt/NdD+lFUS6dgLYkHRuk37MwilLODn68qKT8K6hk3DutwSXQxed8SwFgoLnH4s29kpUhItW0ETHM8FjpH1Tz44KuR4seMgXnAFYWp3LR45QPf+RHTgCowmb5pd9KBr1QfbTGeUDCufgg3HrkYRsD+Qw7owoAqn92lGFZ38nzOonnboVT26Dg7Z/646hPkRE2gxDMLjckKc+PJQtoogbpx2zxZMR70O6XjXuPaSbOuGaWprJIPyHNjemwcgcIttWqZ/RuRdaM6lVTgyvzTnXdCwfpVnnJcfAoszZGYMgqP8z3MV6Cmp+xRSG/9HOk2EEtEXtF/nWTTRxK9XZdUUR8IF+rVZ3KqY6/gz7xkreYtCR14eBMYcmAGIh+qhBSKUa3mqqL19/g1dpbDRW5j6WcPpYSAl5ol05bApgnlYg=
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: 9f33ed8c-6ca0-49c6-b880-aaedc7dd44e2
  app: nodejs-tutorial
  on:
    repo: programming101tutorial/nodejs-tutorial
  skip_cleanup: 'true'
