language: node_js
node_js:
- 12
cache: npm
install:
- npm ci
addons:
  sonarcloud:
    organization: programming101tutorial
    token:
      secure: ZANmuTqAD7IiQXINyPFyl7S8SifnUU90/OZC0ZCsNQ5clL9f0vyeWGIUykH5aBPqaZTfinRQDAxaM8P12IsgEHM994GqFrg0w+eX5o0vFfJ9UPGb+2FEGKt4KDjDTrxIi8FXLwLU9vGC2aXcf2dPMXhFrqDetudeH3OorUtUohFQ8gmiGfnLerYGc0LbuVLK97R5iuhXPzgvsosGd42Mpyu9pKapc2NmLnk6+5RpXrvbeRgbKFQIMt4/OyYLLgjJ045xt/NdD+lFUS6dgLYkHRuk37MwilLODn68qKT8K6hk3DutwSXQxed8SwFgoLnH4s29kpUhItW0ETHM8FjpH1Tz44KuR4seMgXnAFYWp3LR45QPf+RHTgCowmb5pd9KBr1QfbTGeUDCufgg3HrkYRsD+Qw7owoAqn92lGFZ38nzOonnboVT26Dg7Z/646hPkRE2gxDMLjckKc+PJQtoogbpx2zxZMR70O6XjXuPaSbOuGaWprJIPyHNjemwcgcIttWqZ/RuRdaM6lVTgyvzTnXdCwfpVnnJcfAoszZGYMgqP8z3MV6Cmp+xRSG/9HOk2EEtEXtF/nWTTRxK9XZdUUR8IF+rVZ3KqY6/gz7xkreYtCR14eBMYcmAGIh+qhBSKUa3mqqL19/g1dpbDRW5j6WcPpYSAl5ol05bApgnlYg=
script:
- npm run test
deploy:
  provider: heroku
  api_key: 9f33ed8c-6ca0-49c6-b880-aaedc7dd44e2
    # secure: kcxY5Gf5wNC9+iSNsG6sTXNAwjUNhsFQ4hWlh4qaWNPBThUMFOxmLKkWXHim+keHFNOC/k+0ufGsinDKqxfhZzWHfUPorVvfnphAIMBwsgLMT99zzPCaArIJHBU6I+LrRWv+fEPQZ83kFPHveos9AFvpLsxr3bbM4+tJerPIft5ENtTQJ/NcQX7mkTg/ngWZDQQJwnAu6eqR9yr75j/9+hpzOy+119FFsggZV8MqC5ILziVCirBbaj5S51uxRlrs2mhfVZWIk42glZSaNBRM2FMJcae5XZZP8dAnrGVgE6vR9+1Cfnxl1eC+eoOsrnFYtNtFXIvoW3RAygaLzWnhb+SyZQfMwzk8N7qi3Z/Jr7wtHzh38w6qV6rZUxGtcPuz2pLY4AzQobQ0soZsGcgk+KWqLYJIOY8Tx1gLn8Ax/sHIHEjyfPQ6MXc0H6QxOyfBc6Wd7sdDPpewITfAasR4IovrIc/e5BGmN7/WJmLMGJzHGCG8PW6MyoEdUxX3EjLGGlIgRiOMr4ueYgMKRGGmCl2OoPLfh+AKibMSSkJuDxLC4NHk7Y0LaPgQMAFcp7iNrDmPNZUzM8w7mBWuiXk+lCkZjZUk/RxXbK/BVB3QDE8HUNZbv0MmDLdj2dwEv27F7c+EFygNlJ/whiCB5MFFL5NwtSnZb+SvdRM97SNAEjc=
  app: nodejstutorial1
  # on:
  #   repo: programming101tutorial/nodejs-tutorial
  # skip_cleanup: 'true'
